# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'shary'
    metrics_path: '/actuator/prometheus'  # Correct path to the Spring Boot metrics endpoint
    static_configs:
      - targets: ['shary:8080']  # Service name and port


